<?xml version="1.0"?>
<definitions elementName="Weather"
             targetNamespace="http://billing.bpel.tests.sca4j.org"
             xmlns:tns="http://billing.bpel.tests.sca4j.org"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
       <schema targetNamespace="http://billing.bpel.tests.sca4j.org" xmlns="http://www.w3.org/2001/XMLSchema">         
            <complexType elementName="BillingRequest">
                <sequence>
                    <element elementName="itemCode" type="string"/>
                    <element elementName="billingAddress" type="string"/>
                </sequence>
            </complexType>
            <element elementName="billingRequest" type="tns:BillingRequest" />
            <element elementName="billingResponse" type="int" />
       </schema>
    </types>

    <message elementName="BillRequest">
        <part elementName="request" element="tns:billingRequest"/>
    </message>

    <message elementName="BillResponse">
        <part elementName="response" element="tns:billingResponse"/>
    </message>

    <portType elementName="BillingPortType">
        <operation elementName="bill">
           <input message="tns:BillRequest"/>
           <output message="tns:BillResponse"/>
        </operation>
    </portType>

    <binding elementName="BillingSoapBinding" type="tns:BillingPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation elementName="bill">
           <soap:operation soapAction="http://example.com/bill" />
           <input>
               <soap:body use="literal"/>
           </input>
           <output>
               <soap:body use="literal"/>
           </output>
        </operation>
    </binding>

    <service elementName="BillingService">
        <port elementName="BillingPort" binding="tns:BillingSoapBinding">
           <soap:address location="http://example.com/billing"/>
        </port>
    </service>
    
    <plnk:partnerLinkType elementName="BillingPartnerLink">
        <plnk:role elementName="billingService" portType="tns:BillingPortType" />
    </plnk:partnerLinkType>

</definitions>