Insert into ROUTING_CONFIG_ON_VALUE_DATE (ID,CURRENCY,CLEARING_MECHANISM,CLEARING_PERIOD,THRESHOLD_AMOUNT,CHARGE) values (1,'GBP','BACS',2,10000000,0)
/
Insert into ROUTING_CONFIG_ON_VALUE_DATE (ID,CURRENCY,CLEARING_MECHANISM,CLEARING_PERIOD,THRESHOLD_AMOUNT,CHARGE) values (2,'GBP','FPS', 0,10000,5)
/
Insert into ROUTING_CONFIG_ON_VALUE_DATE (ID,CURRENCY,CLEARING_MECHANISM,CLEARING_PERIOD,THRESHOLD_AMOUNT,CHARGE) values (3,'GBP','CHAPS',0,10000000,20)
/
Insert into ROUTING_CONFIG_ON_VALUE_DATE (ID,CURRENCY,CLEARING_MECHANISM,CLEARING_PERIOD,THRESHOLD_AMOUNT,CHARGE) values (4,'USD','NACHA',2,10000000,0)
/
Insert into ROUTING_CONFIG_ON_VALUE_DATE (ID,CURRENCY,CLEARING_MECHANISM,CLEARING_PERIOD,THRESHOLD_AMOUNT,CHARGE) values (5,'USD','FEDWIRE',0,10000000,50)
/

Insert into REMITTANCE_ACCOUNT_CONFIG (ID,CLEARING_MECHANISM,BANK_ID,BANK_NAME,ACCOUNT_NUMBER,ACCOUNT_HOLDER_NAME,ACCOUNT_HOLDER_ADDR_LINE1,ACCOUNT_HOLDER_CITY,ACCOUNT_HOLDER_STATE,ACCOUNT_HOLDER_ZIP) values (1,'BACS','123489','BOE','89562374','BACS','ADDR 1','CITY','JJJ','PE2345')
/
Insert into REMITTANCE_ACCOUNT_CONFIG (ID,CLEARING_MECHANISM,BANK_ID,BANK_NAME,ACCOUNT_NUMBER,ACCOUNT_HOLDER_NAME,ACCOUNT_HOLDER_ADDR_LINE1,ACCOUNT_HOLDER_CITY,ACCOUNT_HOLDER_STATE,ACCOUNT_HOLDER_ZIP) values (2,'FPS','456989','BOE','89562374','FPS','ADDR 1','CITY','JJJ','PE2345')
/
Insert into REMITTANCE_ACCOUNT_CONFIG (ID,CLEARING_MECHANISM,BANK_ID,BANK_NAME,ACCOUNT_NUMBER,ACCOUNT_HOLDER_NAME,ACCOUNT_HOLDER_ADDR_LINE1,ACCOUNT_HOLDER_CITY,ACCOUNT_HOLDER_STATE,ACCOUNT_HOLDER_ZIP) values (3,'CHAPS','562389','BOE','89562374','CHAPS','ADDR 1','CITY','JJJ','PE2345')
/
Insert into REMITTANCE_ACCOUNT_CONFIG (ID,CLEARING_MECHANISM,BANK_ID,BANK_NAME,ACCOUNT_NUMBER,ACCOUNT_HOLDER_NAME,ACCOUNT_HOLDER_ADDR_LINE1,ACCOUNT_HOLDER_CITY,ACCOUNT_HOLDER_STATE,ACCOUNT_HOLDER_ZIP) values (4,'FEDWIRE','895689','BONY','78562374','FEDWIRE','ADDR 1','CITY','JJJ','PE2345')
/
Insert into REMITTANCE_ACCOUNT_CONFIG (ID,CLEARING_MECHANISM,BANK_ID,BANK_NAME,ACCOUNT_NUMBER,ACCOUNT_HOLDER_NAME,ACCOUNT_HOLDER_ADDR_LINE1,ACCOUNT_HOLDER_CITY,ACCOUNT_HOLDER_STATE,ACCOUNT_HOLDER_ZIP) values (5,'NACHA','235689','BONY','41562374','NACHA','ADDR 1','CITY','JJJ','PE2345')
/

Insert into OUTPUT_INS_BATCHING_CONFIG (ID,CLEARING_MECHANISM,THRESHOLD_COUNT,THRESHOLD_AMOUNT) values (1,'BACS',1,10000000)
/
Insert into OUTPUT_INS_BATCHING_CONFIG (ID,CLEARING_MECHANISM,THRESHOLD_COUNT,THRESHOLD_AMOUNT) values (2,'FPS',1,99999999)
/
Insert into OUTPUT_INS_BATCHING_CONFIG (ID,CLEARING_MECHANISM,THRESHOLD_COUNT,THRESHOLD_AMOUNT) values (3,'CHAPS',1,99999999)
/
Insert into OUTPUT_INS_BATCHING_CONFIG (ID,CLEARING_MECHANISM,THRESHOLD_COUNT,THRESHOLD_AMOUNT) values (4,'FEDWIRE',1,99999999)
/
Insert into OUTPUT_INS_BATCHING_CONFIG (ID,CLEARING_MECHANISM,THRESHOLD_COUNT,THRESHOLD_AMOUNT) values (5,'NACHA',3,99999999)
/

